[build]
nixPacks = true
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "cd backend && npx prisma migrate deploy && npm start" 